version: "3.7"
services:
    app:
        image: nginx
        ports: 
            - "80:80"
        volumes: 
            - ./conf/app/etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
            - ./src:/var/www/html

    phpfpm:
        image: php:7.4-fpm
        volumes: 
            - ./src:/var/www/html
    
    mysql:
        image: mysql
        environment: 
            MYSQL_DATABASE: DB1
            MYSQL_USER: admin
            MYSQL_PASSWORD: admin123
            MYSQL_ROOT_PASSWORD: admin123